"""构件类型枚举"""

from enum import Enum


class ElementType(str, Enum):
    """构件类型"""

    STAGE_LIFT = "舞台升降机"
    WAGON_STAGE_SYSTEM = "车台系统"
    WAGON_STAGE_DRIVE_SYSTEM = "车台驱动系统"
    TRANSITION_LIFT_SIDE_STAGE = "过渡升降机 - 侧舞台"
    TRANSITION_LIFT_REAR_STAGE = "过渡升降机 - 后舞台"
    TRANSITION_LIFT_UPPER_STAGE_RIGHT = "过渡升降机 - 上舞台右侧"
    TRANSITION_LIFT_UPPER_STAGE_LEFT = "过渡升降机 - 上舞台左侧"
    PERFORMER_LIFT_CART = "演员升降小车"
    REAR_STAGE_TURNTABLE_WAGON = "后舞台转台车台"
    BALLET_WAGON_WITH_FILLER = "芭蕾车台（含填充车台）"
    PERFORMANCE_PLATFORM_SYSTEM = "演出平台系统"
    ORCHESTRA_PIT_LIFT = "乐池升降机"
    ORCHESTRA_PIT_GUARDRAIL = "乐池护栏"
    ORCHESTRA_PIT_SEAT_WAGON = "乐池座椅车台"
    ORCHESTRA_PIT_SAFETY_NET = "乐池保护网"
    SIDE_STAGE_COMPENSATION_LIFT = "侧舞台补偿升降机"
    REAR_STAGE_COMPENSATION_LIFT = "后舞台补偿升降机"
    PROSCENIUM_SAFETY_CURTAIN = "台口安全幕"
    MAIN_CURTAIN_BATTEN = "大幕吊杆 / 大幕机"
    MOVABLE_LIGHTING_BRIDGE_SYSTEM = "活动灯光桥系统"
    MOVABLE_LIGHTING_FRAME = "活动灯光架"
    ELECTRIC_BATTEN = "电动吊杆"
    MOVABLE_LIGHTING_FLY_BRIDGE = "活动灯光渡桥"
    CABLE_REEL = "卷线器"
    SINGLE_POINT_HOIST_SYSTEM = "单点吊机系统"
    SIDE_LIGHT_BEAM = "侧光梁"
    CHAIN_HOIST_SYSTEM = "链式吊机系统"
    BALLET_WAGON_HOIST = "芭蕾车台吊机"
    FIXED_AND_MOVABLE_CURTAIN_TRACK = "固定和活动幕布轨道"
    STAGE_FRONT_TRUSS_SYSTEM = "舞台前部桁架系统"
    STAGE_FRONT_CHAIN_HOIST = "舞台前部链式吊机"
    SPEAKER_GROUP_HOIST = "扬声器组吊机"
    SUBTITLE_SCREEN_HOIST = "字幕屏吊机"
    CROSS_STAGE_CHAIN_HOIST_AUX = "横跨舞台链式吊机系统 - 辅助舞台"
    REAR_STAGE_DOOR = "后舞台门"
    SIDE_STAGE_DOOR = "侧舞台门"
    UPPER_STAGE_LEFT_SOUNDPROOF_DOOR = "上舞台左隔声门"
    UPPER_STAGE_RIGHT_SOUNDPROOF_DOOR = "上舞台右隔声门"
    LOADING_AREA_DOOR = "卸货区门"
    REAR_STAGE_PASSAGE_DOOR = "后舞台通道门"
    REAR_STAGE_PASSAGE_DOOR_RIGHT = "后舞台通道门 - 右侧"
    REAR_STAGE_PASSAGE_DOOR_LEFT = "后舞台通道门 - 左侧"
    REAR_STAGE_ELECTRIC_BATTEN = "后舞台电动吊杆"
    PERFORMANCE_CONTROL_SYSTEM = "演出控制系统"
    ORCHESTRA_PIT_LIFT_CONTROL_SYSTEM = "乐池升降机控制系统"
    CHAIN_HOIST_CONTROL_SYSTEM = "链式吊机控制系统"
    SIDE_STAGE_CHAIN_HOIST_CONTROL_SYSTEM = "侧舞台链式吊机控制系统"
    REAR_STAGE_HOIST_CONTROL_SYSTEM = "后舞台吊机控制系统"
    ACOUSTIC_SHELL = "反声罩"
    MIXING_CONSOLE_LIFT = "调音台升降机"
    MIXING_CONSOLE_LIFT_WAGON = "调音台升降机车台"
    CURTAINS_AND_COVERINGS = "幕布和遮盖物"
    INPUT_AND_PROCESSING_EQUIPMENT = "接入和处理设备"
    SUSPENSION_ACCESSORIES = "悬吊附件"
    SPARE_PARTS = "备件"
    STAGE_FLOOR = "舞台地板"
    AUDITORIUM_VARIABLE_ACOUSTICS = "观众厅可变声学"
    REHEARSAL_HALL_BATTEN_SYSTEM = "排练厅吊杆系统"
    MOVABLE_SEAT_UNIT = "活动坐席单元"
    SECONDARY_WIRING_INSTALLATION = "安装次级布线"
    TRANSPORT_LIFT = "运输升降机"
    SEAT_LIFT = "座椅提升升降机"
    SEAT_WAGON_SYSTEM = "座椅车台系统"
    MOVABLE_BALCONY_UNIT = "可移动楼座单元"
    LATERAL_CHAIN_HOIST_SYSTEM = "横向链式吊机系统"
    TRUSS_SYSTEM = "桁架系统"
    TRACK_BEAM = "轨道梁"
    UNDER_STAGE_CONTROL_SYSTEM = "台下设备控制系统"
    OVER_STAGE_CONTROL_SYSTEM = "台上设备控制式系统"
    AUDITORIUM_ACOUSTIC_CURTAIN = "观众厅吸声幕"
    AUDITORIUM_ACOUSTIC_PANEL = "观众厅吸声板"
